[Unit]
Wants=
After=sound.target
Conflicts=supercollider.service

[Service]
Environment=PI_MIDI_BACKEND=fluidsynth
Environment=PI_DIRECT_ALSA_KEYS=0
Environment=PI_ALSA_KEY_TONE=0
Environment=PI_ALSA_KEY_TONE_FALLBACK=0
